#+TITLE: Quotes

* Tmp

John F. Kennedy's

#+begin_quote
We choose to go to the Moon in this decade and do the other things, *not because
they are easy, but because they are hard*; because that goal will serve to
organize and measure the best of our energies and skills, because that challenge
is one that we are willing to accept, one we are unwilling to postpone, and one
we intend to win, and the others, too.
#+end_quote

Donald Knuth, in "Computer Programming as an Art" (1974),

#+BEGIN_QUOTE
The real problem is that programmers have spent far too much time
worrying about efficiency in the wrong places and at the wrong times;
*premature optimization is the root of all evil* (or at least most of
it) in programming.
#+END_QUOTE

Yoda in "The Empire Strikes Back":

#+BEGIN_QUOTE
You must unlearn what you have learned.
#+END_QUOTE

William Gibson:

#+BEGIN_QUOTE
The future is already here — it's just not very evenly distributed.
#+END_QUOTE

#+BEGIN_QUOTE
If we wish to count lines of code, we should not regard them as lines
produced, but as lines spend.

-- Edsger Dijkstra
#+END_QUOTE

** ??

#+BEGIN_QUOTE
You can't get to the moon by piling up chairs.
#+END_QUOTE


* Chinese

张一鸣 in [[https://www.youtube.com/watch?v=LnvUU3kAioI&t=45s][an interview]]

#+begin_quote
CEO做决断的话，那么我觉得你至少要做到不要让大家不敢说话，不然你就没有信息吸收了。
理想情况下，你可能能够让，不仅你自己有学习机会和试错成本，你可以把这个机会和成本
分摊给团队成员，让他们也有学习机会和试错成本，让他们能做更多决断。
#+end_quote

In [[https://www.youtube.com/watch?v=_PufBTmWbc8][another interview]]:

#+begin_quote
如果你的效率比对手高很多的话，其实通过单纯的烧钱能产生的竞争力是很小的。规模越大，
亏损越大。所以无论是烧钱还是不烧钱，都应该在效率的前提之下。
#+end_quote

from an investor:
#+begin_quote
他的心和表是一致的，所以呢，对于合作伙伴，对于投资人，都是一样的看法，大家都认为
一鸣说的,说什么就是什么。那么让这些东西都是表里如一的，这对于投资人是非常非常重
要的。
#+end_quote

沈南鹏 in [[https://www.youtube.com/watch?v=ibihbj8zVD8][an interview]] and it's 红杉's investing principle:

#+begin_quote
我们希望做一个高成长的企业，他的最早和最重要的投资人。
#+end_quote

in [[https://www.youtube.com/watch?v=JF1DMJzTt_k][another interview]]:

#+begin_quote
投资，在早期，更多的是艺术，不是科学，不是数据。八年以前，有多少人中午晚上吃外卖
的，多少人现在会去吃外卖，现在很多餐厅自己都在做外卖。什么叫艺术呢？就是你对这个
行业的想象力。你说这个团购行业有多大，咱们能不能量化一下，是两百亿呢还是两千亿呢，
还是两万亿？我感觉在当时你还真的很难去把它量化。
#+end_quote

马东 in [[https://www.youtube.com/watch?v=s8MtzIeeozs][an interview]]
#+begin_quote
焦虑是常态，如果焦虑是人生的底色，那每一个阶段焦虑的东西不太一样，不是一个很享受
的事吗，总比你一辈焦虑一件事要舒服一点吧
#+end_quote

he says it is from 陈丹青:
#+begin_quote
有的人到35岁以后，就不喜欢年轻人了，那这样的人就是老人;有的人到了70岁还喜欢年轻
人，那这样的人就是年轻人。
#+end_quote

胡玮炜 in [[https://www.youtube.com/watch?v=jpYSBo1vLdA][an interview]]:

#+begin_quote
连总理都说，这个时代，不是大鱼吃小鱼，而是快鱼吃慢鱼，你的生存的本能让你跑得非常
非常快。
#+end_quote

#+begin_quote
不是说有两大悲剧吗，一个是你永远都实现不了你想要实现的，一个是你已经实现了你想要
实现的。
#+end_quote

米雯娟 in [[https://www.youtube.com/watch?v=gyNflShy2nQ][an interview]]:

#+begin_quote
数学课上经常看英语书，然后看科幻世界，数学老师把我的书都撕掉了，然后扔到我脸上，
然后说你给我滚出去，你是全世界最差的学生。我后来想了想那个老师其实也挺无奈的，他
也很想帮助每个孩子，但是他没有这样的精力，和所谓的这样一个工具。
#+end_quote

#+begin_quote
女性会给自己铁标签，就像胖子会觉得自己很胖，没信心，我从小就很胖，所以我是个胖子；
我原来这个高中没读完对吧，辍学这也是个标签。其实我觉得更多的是，我们自己不要给自
己贴标签，不要给自己设一个局限。可能创业这个事情，的确是有很大的冒险，运气成分在，
真正去做且做成的人，可能他们都需要一些共同的特质，这个特质其实不一定是男女的区别。
#+end_quote

#+begin_quote
我未来的梦想是可以去帮助成千上万的小朋友，更好的学习和成长，然后这个事情没有头。
我们团队里面经常自己讲说，今天做到了几分，如果满分是一百分的话，我们觉得只做到了
一分。
#+end_quote

戴琨 in [[https://www.youtube.com/watch?v=44tq84K9tdA][an interview]]:

#+begin_quote
德州扑克里面其实最关键的问题就是，你其实真真正正你可能打二十把，能赢钱的就那两把。
就15分钟。这15分钟你是不是把注打够了。当你只有一点点的chips的时候，你如果不下注，
你光打底就死了。那在这个时候呢，我觉得是搏大的。就是需要在有胜算的时候all in进去。
我们在第6个月的时候，账面上就剩两三百万美元了。但是到那个位置了你不可能停下来嘛。
你补了5个月，你停下来，你不就证明自己错了吗。于情于理死撑也得撑着。晚上睡不着觉
我就不睡，我就起来跑步，我去跑一个小时，跑到筋疲力尽，我可以把自己累晕过去，但是
我在这种状态下我会保证一个好的睡眠。
#+end_quote

by the interviewer himself:

#+begin_quote
百人以下的公司靠愿景，一千人的团队靠规章制度，一万人的公司靠文化。
#+end_quote

汪建国 in [[https://www.youtube.com/watch?v=8jM54v5EqK8][an interview]]:

#+begin_quote
人的成长过程中会有瓶颈，企业发展过程中会有瓶颈。解决瓶颈的唯一办法实际上是放弃。
这个时候你就像一个抛物线，当你意识到你已经走向了抛物线的顶端的时候，应该大胆去寻
找第二条抛物线。
#+end_quote

韩坤 in [[https://www.youtube.com/watch?v=zNJ32_iYWcA][an interview]]:
#+begin_quote
每一个创业者，每一天都是非常焦虑的，我们特别担心我们在这里高高兴兴的在数我们用户
有多少的时候，旁边有几个特别牛的人，在一个小屋子里面，正在思考怎么来去超越你。那
我希望那个小屋子里的人全部都是我们的人，这样才能降低我们的焦虑。
#+end_quote

周鸿祎 in [[https://www.youtube.com/watch?v=N66EQp59w90&list=PLrybf3rp9BTv77LrkACe-1QH8A7GsLrra&index=23][an interview]]:
#+begin_quote
其实勇士和懦夫在战场上都会感到恐惧，唯一的差别就是勇士能控制这种恐惧，不要让恐惧
控制你。
#+end_quote

曹德旺 in [[https://youtu.be/XBbybKpz6Go][《十年二十人》]]:
# #+begin_quote
# 一个成功的企业家必须有四个自信.
# #+end_quote

#+begin_quote
商道倡导的就是义利兼济。义就是勇于挑战天下，勇于承担责任，勇于挑战未来，作有责任
的企业家。做完了，你不要忘记你要赚钱，因为你是做生意的，商道。你义做得很好，利我
没有关照到，没有后劲了你也活不下去。因此它倡导的是义利相济，这就是信仰。
#+end_quote

程维 in [[https://youtu.be/A2YV8_8nL1U][《十年二十人》]]:

#+begin_quote
努力到无能为力，上天就会给你开一扇窗
#+end_quote

[[http://about.sinosig.com/common/about_sinosig/html/wenhua.shtml][阳光五十字箴言]]:

#+begin_quote
集众家之长 取自我之道

聚业内人才 纳业外贤士

高起点组建 远战略发展

风雨中做事 阳光下做人

走精英之路 创阳光品牌
#+end_quote

* Education

Michael Seibel

#+BEGIN_QUOTE
The best private schools are generous with financial aid.
#+END_QUOTE

Marvin Minsky
#+BEGIN_QUOTE
School is the best thing ever invented to keep you from thinking about
something important for more than a few minutes.
#+END_QUOTE


* Space
Fred Hoyle

#+BEGIN_QUOTE
Space isn't remote at all. It's only an hour's drive away if your car
could go straight upwards.
#+END_QUOTE


* Technology

Linus Torvalds

#+BEGIN_QUOTE
Only wimps use tape backup: real men just upload their important stuff
on ftp, and let the rest of the world mirror it.
#+END_QUOTE

Eric S. Raymond on Plan9's failure.

#+BEGIN_QUOTE
The most dangerous enemy of a better solution is an existing codebase
that is just good enough.
#+END_QUOTE

Richard Feynman

#+BEGIN_QUOTE
What I cannot create, I do not understand.
#+END_QUOTE


* Mathematics

George Box

#+BEGIN_QUOTE
All models are wrong. Some models are useful.
#+END_QUOTE


* China

Napoleon Bonaparte

#+BEGIN_QUOTE
Let China sleep, for when she wakes she will shake the world.
#+END_QUOTE


* Time, Life, Determination, etc

Jeff Bezos in [[https://www.youtube.com/watch?v=jwG_qR6XmDQ][an interview video on Regret Minimization Framework]]:

#+begin_quote
(My boss says) (selling book online) sounds like really a good idea to me. But
it sounds like a BETTER idea for somebody who DIDN'T ALREADY HAVE A GOOD
JOB. Hahahahahhahahahhahahah
#+end_quote

#+begin_quote
I wanted to project myself forward to age 80 and say okay now I'm looking back
on my life I want to have minimized the number of regrets I have. And I knew
that when I was 80, I was not going to regret having tried this. I was now going
to regret having tring to participate in this thing called the internet that I
thought was going to be a really big deal. And I knew that if I failed, I
wouldn't regret that. But I knew one thing I might regret is not ever having
tried and I knew that that would haunt me every day. So when I thought about it
that way, it was an incredibly easy decision, and I think that's very good if
you can project yourself out to the age 80, and think what will I think at that
time, it gets you away from some of the daily pieces of confusion.
#+end_quote

also checkout [[https://www.youtube.com/watch?v=KPbKeNghRYE][It Is Always Day One]]


Julian Shapiro

#+begin_quote
Because every minute spent doing something other than what you love most today
is a minute you’re more likely to regret when you’re 80.
#+end_quote

Henry Ford

#+BEGIN_QUOTE
If I had asked people what they wanted, they would have said – faster
horses.
#+END_QUOTE


Paul Brown

#+BEGIN_QUOTE
When you win, say nothing, when you lose say less.
#+END_QUOTE

Then, when to say a lot? When you are going to do!

Louis Agassiz

#+BEGIN_QUOTE
I cannot afford to waste my time making money.
#+END_QUOTE

Albert Camus

#+BEGIN_QUOTE
Don't wait for the Last Judgement. It takes place every day.
#+END_QUOTE

Bob Dylan
#+BEGIN_QUOTE
A man is a success if he gets up in the morning and gets to bed at
night, and in between he does what he wants to do.
#+END_QUOTE

Mark Twain

#+BEGIN_QUOTE
Always do right. This will gratify some people and astonish the rest.
#+END_QUOTE

Neil Gaiman

#+BEGIN_QUOTE
When you are scared, but do it anyway, that's brave.
#+END_QUOTE

Bernard M. Baruch

#+BEGIN_QUOTE
Be who you are and say what you feel, because those who mind don't
matter, and those who matter don't mind.
#+END_QUOTE

Michel de Montaigne
#+BEGIN_QUOTE
There is no conversation more boring than the one where everybody
agrees.
#+END_QUOTE

Albert Szent-Gyorgi
#+BEGIN_QUOTE
Discovery is seeing what everyone else has seen and thinking what no
one else has thought.
#+END_QUOTE

* Art

John A. Locke

#+BEGIN_QUOTE
That which is static and repetitive is boring. That which is dynamic
and random is confusing. In between lies art.
#+END_QUOTE

Alan Turing
#+BEGIN_QUOTE
Science is a differential equation. Religion is a boundary condition.
#+END_QUOTE



* By People

** Sam Altman

#+BEGIN_QUOTE
The most successful founders are the sort of people who are low-stress
to work with because you feel “he or she will get it done, no matter
what it is.
#+END_QUOTE

#+BEGIN_QUOTE
Mediocre engineers do not build great companies.
#+END_QUOTE

#+BEGIN_QUOTE
The best companies are almost always mission oriented
#+END_QUOTE

#+BEGIN_QUOTE
When doing hiring:
- are they smart?
- do they get things done?
- do I want to spend a lot of time around them?
#+END_QUOTE

** Steve Jobs
2010 interview:

#+BEGIN_QUOTE
What I love about the consumer market, that I always hated about the
enterprise market, is that we come up with a product, we try to tell
everybody about it, and every person votes for themselves. They go
'yes' or 'no,' and if enough of them say 'yes,' we get to come to work
tomorrow. That's how it works. It's really simple. With the enterprise
market, it's not so simple. The people that use the products don't
decide for themselves, and the people that make those decisions
sometimes are confused. We love just trying to make the best products
in the world for people and having them tell us by how they vote with
their wallets whether we're on track or not.
#+END_QUOTE

#+BEGIN_QUOTE
Just because we're competing with someone doesn't mean we have to be rude.
#+END_QUOTE

From Steve Jobs’ Commencement address on June 12, 2005:

#+BEGIN_QUOTE
My third story is about death.

When I was 17, I read a quote that went something like: *“If you live
each day as if it was your last, someday you’ll most certainly be
right.”* It made an impression on me, and since then, for the past 33
years, I have looked in the mirror every morning and asked myself:
*“If today were the last day of my life, would I want to do what I am
about to do today?” And whenever the answer has been “No” for too many
days in a row, I know I need to change something.*

Remembering that I’ll be dead soon is the most important tool I’ve
ever encountered to help me make the big choices in life. Because
*almost everything — all external expectations, all pride, all fear of
embarrassment or failure — these things just fall away in the face of
death, leaving only what is truly important.* Remembering that you are
going to die is the best way I know to avoid the trap of thinking you
have something to lose. *You are already naked. There is no reason not
to follow your heart.*

About a year ago I was diagnosed with cancer. I had a scan at 7:30 in
the morning, and it clearly showed a tumor on my pancreas. I didn’t
even know what a pancreas was. The doctors told me this was almost
certainly a type of cancer that is incurable, and that I should expect
to live no longer than three to six months. My doctor advised me to go
home and get my affairs in order, which is doctor’s code for prepare
to die. It means to try to tell your kids everything you thought you’d
have the next 10 years to tell them in just a few months. It means to
make sure everything is buttoned up so that it will be as easy as
possible for your family. It means to say your goodbyes.

I lived with that diagnosis all day. Later that evening I had a
biopsy, where they stuck an endoscope down my throat, through my
stomach and into my intestines, put a needle into my pancreas and got
a few cells from the tumor. I was sedated, but my wife, who was there,
told me that when they viewed the cells under a microscope the doctors
started crying because it turned out to be a very rare form of
pancreatic cancer that is curable with surgery. I had the surgery and
I’m fine now.

This was the closest I’ve been to facing death, and I hope it’s the
closest I get for a few more decades. Having lived through it, I can
now say this to you with a bit more certainty than when death was a
useful but purely intellectual concept:

No one wants to die. Even people who want to go to heaven don’t want
to die to get there. And yet death is the destination we all share. No
one has ever escaped it. And that is as it should be, because Death is
very likely the single best invention of Life. It is Life’s change
agent. It clears out the old to make way for the new. Right now the
new is you, but someday not too long from now, you will gradually
become the old and be cleared away. Sorry to be so dramatic, but it is
quite true.

*Your time is limited, so don’t waste it living someone else’s
life. Don’t be trapped by dogma — which is living with the results of
other people’s thinking. Don’t let the noise of others’ opinions drown
out your own inner voice. And most important, have the courage to
follow your heart and intuition. They somehow already know what you
truly want to become. Everything else is secondary.*
#+END_QUOTE

#+BEGIN_QUOTE
Here’s to the crazy ones, the misfits, the rebels, the troublemakers,
the round pegs in the square holes… The ones who see things
differently — they’re not fond of rules… You can quote them, disagree
with them, glorify or vilify them, but the only thing you can’t do is
ignore them because they change things… They push the human race
forward, and while some may see them as the crazy ones, we see genius,
because the ones who are crazy enough to think that they can change
the world, are the ones who do.
#+END_QUOTE

#+BEGIN_QUOTE
It’s better to be a pirate than to join the navy.
#+END_QUOTE

#+BEGIN_QUOTE
Stay hungry. Stay foolish.
#+END_QUOTE

#+BEGIN_QUOTE
Your work is going to fill a large part of your life, and the only way
to be truly satisfied is to do what you believe is great work. And the
only way to do great work is to love what you do. If you haven’t found
it yet, keep looking. Don’t settle. As with all matters of the heart,
you’ll know when you find it.
#+END_QUOTE

#+BEGIN_QUOTE
If you want to live your life in a creative way, as an artist, you
have to not look back too much. You have to be willing to take
whatever you’ve done and whoever you were and throw them away.
#+END_QUOTE

** Alan Kay

#+BEGIN_QUOTE
People who are really serious about software should make their own hardware.
#+END_QUOTE

#+BEGIN_QUOTE
If you want to make money, don't start a startup; start an
industry. That way you make trillions instead of billions.
#+END_QUOTE

#+BEGIN_QUOTE
Don't do incremental things; do evolution ones.
#+END_QUOTE

#+BEGIN_QUOTE
I had the fortune or misfortune to learn how to read fluently starting
at the age of three. So I had read maybe 150 books by the time I hit
1st grade. And I already knew that the teachers were lying to me.
#+END_QUOTE

#+BEGIN_QUOTE
If you don't fail at least 90 percent of the time, you're not aiming
high enough.
#+END_QUOTE


** Albert Einstein

#+BEGIN_QUOTE
Two things are infinite: the universe and human stupidity; and I'm not
sure about the universe
#+END_QUOTE

#+BEGIN_QUOTE
There are only two ways to live your life. One is as though nothing is
a miracle. The other is as though everything is a miracle.
#+END_QUOTE



** Paul Graham

#+BEGIN_QUOTE
There are few sources of energy so powerful as a procrastinating
college student.
#+END_QUOTE

#+BEGIN_QUOTE
Odds are you just think whatever you're told.
#+END_QUOTE

#+BEGIN_QUOTE
You need three things to create a successful startup: to start with
good people, to make something customers actually want, and to spend
as little money as possible.
#+END_QUOTE

#+BEGIN_QUOTE
It's important for nerds to realize, too, that school is not
life. School is a strange, artificial thing, half sterile and half
feral. It's all-encompassing, like life, but it isn't the real
thing. It's only temporary, and if you look, you can see beyond it
even while you're still in it.
#+END_QUOTE

#+BEGIN_QUOTE
It’s hard to do a really good job on anything you don’t think about in
the shower.
#+END_QUOTE

# #+BEGIN_QUOTE
# You are not doing the right thing if you don't think about it in the
# shower; you are doing a terrible thing if you are cursing it in the
# shower. -- By Hebi Li
# #+END_QUOTE

#+BEGIN_QUOTE
But if you're trying to choose between two theories and one gives you
an excuse for being lazy, the other one is probably right.
#+END_QUOTE

#+BEGIN_QUOTE
Don't ignore your dreams; don't work too much; say what you think;
cultivate friendships; be happy.
#+END_QUOTE

#+BEGIN_QUOTE
You don't need people to give you advice that doesn't surprise you.
#+END_QUOTE

#+begin_quote
The difference between design and research seems to be a question of new versus
good. Design doesn’t have to be new, but it has to be good. Research doesn’t
have to be good, but it has to be new.
#+end_quote


** Peter Norvig
#+BEGIN_QUOTE
PowerPoint doesn't kill meetings. People kill meetings. But using
PowerPoint is like having a loaded AK-47 on the table: You can do very
bad things with it.
#+END_QUOTE


** Pablo Picasso

#+BEGIN_QUOTE
Art is a lie that tells the truth
#+END_QUOTE

#+BEGIN_QUOTE
Good artists copy, great artists steal.
#+END_QUOTE

#+BEGIN_QUOTE
Learn the rules like a pro, so you can break them like an artist.
#+END_QUOTE

#+BEGIN_QUOTE
Computers are useless. They can only give you answers.
#+END_QUOTE





** Wayne Gretzky


#+BEGIN_QUOTE
I skate to where the puck is going to be, not where it has been.
#+END_QUOTE

#+BEGIN_QUOTE
Only one thing is ever guaranteed, that is that you will definitely
not achieve the goal if you don’t take the shot.
#+END_QUOTE

#+BEGIN_QUOTE
The day I stop giving is the day I stop receiving. The day I stop
learning is the day I stop growing. You miss 100% of the shots you
don’t take.
#+END_QUOTE

#+BEGIN_QUOTE
If you surround yourself with quality people and great friends, the
sky’s the limit.
#+END_QUOTE

#+BEGIN_QUOTE
Not doing it is certainly the best way to not getting it.
#+END_QUOTE
