#+TITLE: Quotes

* Steve Jobs

#+BEGIN_QUOTE
Your time is limited, don’t waste it living someone else’s life. Don’t
be trapped by dogma, which is living the result of other people’s
thinking. Don’t let the noise of other opinions drown your own inner
voice. And most important, have the courage to follow your heart and
intuition, they somehow already know what you truly want to
become. Everything else is secondary.
#+END_QUOTE

#+BEGIN_QUOTE
Here’s to the crazy ones, the misfits, the rebels, the troublemakers,
the round pegs in the square holes… The ones who see things
differently — they’re not fond of rules… You can quote them, disagree
with them, glorify or vilify them, but the only thing you can’t do is
ignore them because they change things… They push the human race
forward, and while some may see them as the crazy ones, we see genius,
because the ones who are crazy enough to think that they can change
the world, are the ones who do.
#+END_QUOTE

#+BEGIN_QUOTE
It’s better to be a pirate than to join the navy.
#+END_QUOTE

#+BEGIN_QUOTE
Stay hungry. Stay foolish.
#+END_QUOTE

#+BEGIN_QUOTE
Your work is going to fill a large part of your life, and the only way
to be truly satisfied is to do what you believe is great work. And the
only way to do great work is to love what you do. If you haven’t found
it yet, keep looking. Don’t settle. As with all matters of the heart,
you’ll know when you find it.
#+END_QUOTE

#+BEGIN_QUOTE
If you want to live your life in a creative way, as an artist, you
have to not look back too much. You have to be willing to take
whatever you’ve done and whoever you were and throw them away.
#+END_QUOTE
