#+TITLE: 诗词曲
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../assets/font.css" />

* 老子 道德经

道可道，非常道。名可名，非常名。无名天地之始；有名万物之母。故常无欲，
以观其妙；常有欲，以观其徼(jiǎo)。此两者，同出而异名，同谓之玄。玄之
又玄，衆妙之门。

天下皆知美之为美，斯恶已。皆知善之为善，斯不善已。故有无相生，难易相成，
长短相较，高下相倾，音声相和，前后相随。是以圣人处无为之事，行不言之教；
万物作焉而不辞，生而不有。为而不恃，功成而弗居。夫唯弗居，是以不去。

不尚贤，使民不争；不贵难得之货，使民不为盗；不见可欲，使心不乱。是以圣
人之治，虚其心，实其腹，弱其志，强其骨。常使民无知无欲。使夫知者不敢为
也。为无为，则无不治。

道冲，而用之或不盈。渊兮，似万物之宗。挫其锐，解其纷，和其光，同其尘。
湛兮，似或存。吾不知谁之子，象帝之先。

天地不仁，以万物为刍狗；圣人不仁，以百姓为刍狗。天地之间，其犹橐(tuó)
龠(yuè)乎？虚而不屈，动而愈出。多言数穷，不如守中。

谷神不死，是谓玄牝(pìn)。玄牝之门，是谓天地根。绵绵若存，用之不勤。

天长地久。天地所以能长且久者，以其不自生，故能长生。是以圣人后其身而身
先；外其身而身存。非以其无私耶？故能成其私。

上善若水。水善利万物而不争，处衆人之所恶，故几于道。居善地，心善渊，与
善仁，言善信，正善治，事善能，动善时。夫唯不争，故无尤。

持而盈之，不如其已；揣而锐之，不可长保。金玉满堂，莫之能守；富贵而骄，
自遗其咎。功遂身退天之道。

载营魄抱一，能无离乎？专气致柔，能婴儿乎？涤除玄览，能无疵乎？爱民治国，
能无知乎？天门开阖，能为雌乎？明白四达，能无知乎？生之、畜之，生而不有，
为而不恃，长而不宰，是谓玄德。

三十辐，共一毂(gǔ)，当其无，有车之用。埏(shān)埴(zhí)以为器，当其无，
有器之用。凿户牖(yǒu)以为室，当其无，有室之用。故有之以为利，无之以为
用。

* 声律启蒙

** 一·东

云对雨，雪对风，晚照对晴空。来鸿对去燕，宿鸟对鸣虫。三尺剑，六钧弓，岭
北对江东。人间清暑殿，天上广寒宫。两岸晓烟杨柳绿，一园春雨杏花红。两鬓
风霜，途次早行之客;一蓑烟雨，溪边晚钓之翁。

沿对革，异对同，白叟对黄童。江风对海雾，牧子对渔翁。颜巷陋，阮途穷，冀
北对辽东。池中濯足水，门外打头风。梁帝讲经同泰寺，汉皇置酒未央宫。尘虑
萦心，懒抚七弦绿绮;霜华满鬓，羞看百炼青铜。

贫对富，塞对通，野叟对溪童。鬓皤(pó)对眉绿，齿皓对唇红。天浩浩，日融融，
佩剑对弯弓。半溪流水绿，千树落花红。野渡燕穿杨柳雨，芳池鱼戏芰荷风。女
子眉纤，额下现一弯新月;男儿气壮，胸中吐万丈长虹。

** 二·冬
春对夏，秋对冬。暮鼓对晨钟。观山对玩水，绿竹对苍松。冯妇虎，叶公龙。舞
蝶对鸣蛩。衔泥双紫燕，课蜜几黄蜂。春日园中莺恰恰，秋天塞外雁雍雍。秦岭
云横，迢递八千远路；巫山雨洗，嵯峨十二危峰。

明对暗，淡对浓。上智对中庸。镜奁对衣笥，野杵对村舂。花灼烁，草蒙茸。九
夏对三冬。台高名戏马，斋小号蟠龙。手擘(bò)蟹螯从毕卓，身披鹤氅(chǎng)
自王恭。五老峰高，秀插云霄如玉笔；三姑石大，响传风雨若金镛。

仁对义，让对恭。禹舜对羲农。雪花对云叶，芍药对芙蓉。陈后主，汉中宗。绣
虎对雕龙。柳塘风淡淡，花圃月浓浓。春日正宜朝看蝶，秋风那更夜闻蛩
(qióng)。战士邀功，必借干戈成勇武；逸民适志，须凭诗酒养疏慵。

** 三·江

楼对阁，户对窗。巨海对长江。蓉裳对蕙帐，玉斝对银釭。青布幔，碧油幢。宝
剑对金缸。忠心安社稷，利口覆家邦。世祖中兴延马武，桀王失道杀龙逄。秋雨
潇潇，漫烂黄花都满径；春风袅袅，扶疏绿竹正盈窗。

旌对旆，盖对幢。故国对他邦。千山对万水，九泽对三江。山岌岌，水淙淙。鼓
振对钟撞。清风生酒舍，皓月照书窗。阵上倒戈辛纣战，道旁系剑子婴降。夏日
池塘，出没浴波鸥对对；春风帘幕，往来营垒燕双双。

** 四·支
茶对酒，赋对诗。燕子对莺儿。栽花对种竹，落絮对游丝。四目颉，一足夔。鸲
鹆对鹭鸶。半池红菡(hàn)萏(dàn)，一架白荼縻。几阵秋风能应候，一犁春雨甚
知时。智伯恩深，国士吞变形之炭；羊公德大，邑人竖堕泪之碑。

行对止，速对迟。舞剑对围棋。花笺对草字，竹简对毛锥。汾水鼎，岘山碑。虎
豹对熊罴(pí)。花开红锦绣，水漾碧琉璃。去妇因探邻舍枣，出妻为种后园葵。
笛韵和谐，仙管恰从云里降；橹声咿轧，渔舟正向雪中移。

戈对甲，鼓对旗。紫燕对黄鹂。梅酸对李苦，青眼对白眉。三弄笛，一围棋。雨
打对风吹。海棠春睡早，杨柳昼眠迟。张骏曾为槐树赋，杜陵不作海棠诗。晋士
特奇，可比一斑之豹；唐儒博识，堪为五总之龟。

** 五·徵(zhēng)

来对往，密对稀。燕舞对莺飞。风清对月朗，露重对烟微。霜菊瘦，雨梅肥。客
路对渔矶。晚霞舒锦绣，朝露缀珠玑。夏暑客思欹石枕，秋寒妇念寄边衣。春水
才深，青草岸边渔父去；夕阳半落，绿莎原上牧童归。

宽对猛，是对非。服美对乘肥。珊瑚对玳瑁，锦绣对珠玑。桃灼灼，柳依依。绿
暗对红稀。窗前莺并语，帘外燕双飞。汉致太平三尺剑，周臻大定一戎衣。吟成
赏月之诗，只愁月堕；斟满送春之酒，惟憾春归。

声对色，饱对饥。虎节对龙旗。杨花对桂叶，白简对朱衣。尨也吠，燕于飞。荡
荡对巍巍。春暄资日气，秋冷借霜威。出使振威冯奉世，治民异等尹翁归。燕我
弟兄，载咏棣棠韡(wěi)韡；命伊将帅，为歌杨柳依依。

** 六·鱼
无对有，实对虚。作赋对观书。绿窗对朱户，宝马对香车。伯乐马，浩然驴。弋
雁对求鱼。分金齐鲍叔，奉璧蔺相如。掷地金声孙绰赋，回文锦字窦滔书。未遇
殷宗，胥靡困傅岩之筑；既逢周后，太公舍渭水之渔。

终对始，疾对徐。短褐对华裾。六朝对三国，天禄对石渠。千字策，八行书。有
若对相如。花残无戏蝶，藻密有潜鱼。落叶舞风高复下，小荷浮水卷还舒。爱见
人长，共服宣尼休假盖；恐彰已吝，谁知阮裕竟焚车。

麟对凤，鳖对鱼。内史对中书。犁锄对耒耜，畎浍对郊墟。犀角带，象牙梳。驷
马对安车。青衣能报赦，黄耳解传书。庭畔有人持短剑，门前无客曳长裾。波浪
拍船，骇舟人之水宿；峰峦绕舍，乐隐者之山居。

** 七·虞
金对玉，宝对珠。玉兔对金乌。孤舟对短棹，一雁对双凫。横醉眼，捻吟须。李
白对杨朱。秋霜多过雁，夜月有啼乌。日暖园林花易赏，雪寒村舍酒难沽。人处
岭南，善探巨象口中齿；客居江右，偶夺骊龙颔下珠。

贤对圣，智对愚。傅粉对施朱。名缰对利锁，挈(kē)榼对提壶。鸠哺子，燕调雏。
石帐对郇厨。烟轻笼岸柳，风急撼庭梧。鸜(qú)眼一方端石砚，龙涎三炷博山垆。
曲沼鱼多，可使渔人结网；平畴兔少，漫劳耕者守株。

秦对赵，越对吴。钓客对耕夫。箕(jī)裘(qiú)对杖履，杞梓对桑榆。天欲晓，
日将晡。狡兔对妖狐。读书甘刺股，煮粥惜焚须。韩信武能平四海，左思文足赋
三都。嘉遁幽人，适志竹篱茅舍；胜游公子，玩情柳陌花衢(qú)。

** 八·齐

岩对岫(xiù)，涧对溪。远岸对危堤。鹤长对凫短，水雁对山鸡。星拱北，月流
西。汉露对汤霓。桃林牛已放，虞坂马长嘶。叔侄去官闻广受，弟兄让国有夷齐。
三月春浓，芍药丛中蝴蝶舞；五更天晓，海棠枝上子规啼。

云对雨，水对泥。白璧对玄圭。献瓜对投李，禁鼓对征鼙(pí)。徐稚榻，鲁班梯。
凤翥(zhù)对鸾栖，有官清似水，无客醉如泥。截发惟闻陶侃母，断机只有乐羊
妻。秋望佳人，目送楼头千里雁；早行远客，梦惊枕上五更鸡。

熊对虎，象对犀。霹雳对虹霓。杜鹃对孔雀，桂岭对梅溪。萧史凤，宋宗鸡。远
近对高低。水寒鱼不跃，林茂鸟频栖。杨柳和烟彭泽县，桃花流水武陵溪。公子
追欢，闲骤玉骢(cōng)游绮陌；佳人倦绣，闷欹(yī)珊枕掩香闺。

* 诗歌
** 普天乐 -- 滕斌

叹光阴，如流水。区区终日，枉用心机。辞是非，绝名利。

笔砚诗书为活计，乐虀盐稚子山妻。茅舍数间，田园二顷，归去来兮。
** 苏幕遮 -- 范仲淹

碧云天，黄叶地，秋色连波，波上寒烟翠。山映斜阳天接水，芳草无情，更在斜
阳外。

黯乡魂，追旅思。夜夜除非，好梦留人睡。明月楼高休独倚，酒入愁肠，化作相
思泪。

** 御街行 -- 范仲淹

纷纷坠叶飘香砌，夜寂静，寒声碎。真珠帘卷玉楼空，天淡银河垂地。年年今夜，
月华如练，长是人千里。

愁肠已断无由醉，酒未到，先成泪。残灯明灭枕头欹，谙尽孤眠滋味。都来此事，
眉间心上，无计相回避。

** 宴山亭 北行见杏花 -- 赵佶

裁翦冰绡，轻叠数重，淡着燕脂匀注。新样靓妆，艳溢香融，羞杀蕊珠宫女。易
得凋零，更多少无情风雨？愁苦，问院落凄凉，几番春暮？

凭寄离恨重重，者双燕何曾会人言语？天遥地远，万水千山，知他故宫何处？怎
不思量？除梦里有时曾去。无据，和梦也新来不做。


** 木兰花 -- 钱惟演

城上风光莺语乱，城下烟波春拍岸。

绿杨芳草几时休，泪眼愁肠先已断。

情怀渐觉成衰晚，鸾镜朱颜惊暗换。

昔年多病厌芳尊，今日芳尊惟恐浅。

** 无题 -- 李商隐

相见时难别亦难，东风无力百花残。

春蚕到死丝方尽，蜡炬成灰泪始干。

晓镜但愁云鬓改，夜吟应觉月光寒。

蓬山此去无多路，青鸟殷勤为探看。

* 流行歌词

** 老男孩

那是我日夜思念，深深爱着的人啊。
到底我该如何表达，她会接受我吗。

也许永远都不会跟她说出那句话，
注定我要浪迹天涯，怎么能有牵挂。

梦想总是遥不可及，是不是应该放弃。
花开花落又是一季，春天啊你在哪里。

青春如同奔流的江河，一去不回来不及道别。
只剩下麻木的我没有了当年的热血。

看那漫天飘零的花朵，在最美丽的时刻凋谢。
有谁会记得这世界她来过。

转眼过去多年时间，多少离合悲欢。
曾经志在四方少年，羡慕南飞的雁。

各自奔前程的身影，匆匆渐行渐远。
未来在哪里平凡，啊谁给我答案。

那时陪伴我的人啊，你们如今在何方。
我曾经爱过的人啊，现在是什么模样。

当初的愿望实现了吗，事到如今只好祭奠吗。
任岁月风干理想，再也找不到真的我。

抬头仰望这满天星河，那时候陪伴着我的那颗，
这里的故事你是否还记得？


生活像一把无情刻刀，改变了我们模样。
未曾绽放就要枯萎吗，我有过梦想。

青春如同奔流的江河，一去不回来不及道别。
只剩下麻木的我没有了当年的热血。

看那漫天飘零的花朵，在最美丽的时刻凋谢。
有谁会记得这世界她曾经来过。

当初的愿望实现了吗，事到如今只好祭奠吗。
任岁月风干理想，再也找不到真的我。

抬头仰望这满天星河，那时候陪伴着我的那颗，
这里的故事你是否还记得？

如果有明天，祝福你亲爱的。

** 天下

一生有爱 何惧风飞沙
悲白发留不住芳华 
