#+TITLE: Reading

* The Moon and Sixpence 月亮与六便士
by William Somerset Maugham

#+begin_quote
我不想谋生，我想生活。 －－ 奥斯卡×王尔德
#+end_quote

本书书名来源于《泰晤士报》的书评“为天上的月亮神魂颠倒，对脚下的六便士
视而不见”。此名信手拈来，也倒符和主人公不羁的性格。

主人公原型为高更（Gauguin），其于孤倒岛墙壁上创作 “Where do we come
from? What are we? Where are we going?”

即使毛姆不是“我”，即使斯特里克兰才桀骜不驯，“我”内心也是如此狂热，从而
对斯特里克兰的表现是认同的，并与其成为朋友，毛姆才会创作斯特里克兰的形
象：

#+begin_quote
我的血液里有一种强烈的冲动，渴望一种桀骜不驯的旅程。这样的安逸总让我惊
惧。我的心渴望更加惊险的生活。只要我能有所改变－－改变和不可预知的冒险，
我将踏上嶙峋怪石，哪怕激流险滩。
#+end_quote

斯特里克兰在大部分人的标准下，自私，一意孤行，这种人不被认可。然而，又
有多少人披着良心的外衣被其奴役，只为被大众价值认可？

只有诚实，真挚的灵魂才感知得到美：

#+begin_quote
人们随随便便谈论美，却不知美为何物，这个词已被用滥了，失去了它原有的力
量；所有的鸡零狗碎都以美为名，使美本身的含义荡然无存。

但是斯特洛夫，这个本性难移的小丑，对于美，却有着诚实，真挚的理解，就像
他灵魂的诚实，真挚一样。美对他来说，就像信徒心中的上帝，当他真看见了，
却感到害怕。
#+end_quote



** 小人物
小人物常态：
#+begin_quote
上校茫然地望向空中，我不知道有认能像他这样，故作清白。
#+end_quote

斯特里克兰夫人被迫开了一家打印店谋生，却虚荣掩饰：
#+begin_quote
但她觉得，自己开门谋生不那么体面，所以总提醒你，她出身高贵。与人谈话，
她时不时就提她认识的一些人物，让你知道，她社会地位一点儿不低。
#+end_quote

斯特里克兰夫人是痛苦的，这痛苦不会带来“高贵”，而是仇恨：
#+begin_quote
让人行动高尚的，是自满得意；而痛苦，往往使人变得心胸狭窄，充满仇恨。
#+end_quote

