#+TITLE: Reading

* The Moon and Sixpence 月亮与六便士
by William Somerset Maugham

#+begin_quote
我不想谋生，我想生活。 －－ 奥斯卡×王尔德
#+end_quote

本书书名来源于《泰晤士报》的书评“为天上的月亮神魂颠倒，对脚下的六便士
视而不见”。此名信手拈来，也倒符和主人公不羁的性格。

主人公原型为高更（Gauguin），其于孤倒岛墙壁上创作 “Where do we come
from? What are we? Where are we going?”

即使毛姆不是“我”，即使斯特里克兰才桀骜不驯，“我”内心也是如此狂热，从而
对斯特里克兰的表现是认同的，并与其成为朋友，毛姆才会创作斯特里克兰的形
象：

#+begin_quote
我的血液里有一种强烈的冲动，渴望一种桀骜不驯的旅程。这样的安逸总让我惊
惧。我的心渴望更加惊险的生活。只要我能有所改变－－改变和不可预知的冒险，
我将踏上嶙峋怪石，哪怕激流险滩。
#+end_quote

斯特里克兰在大部分人的标准下，自私，一意孤行，这种人不被认可。然而，又
有多少人披着良心的外衣被其奴役，只为被大众价值认可？

只有诚实，真挚的灵魂才感知得到美：

#+begin_quote
人们随随便便谈论美，却不知美为何物，这个词已被用滥了，失去了它原有的力
量；所有的鸡零狗碎都以美为名，使美本身的含义荡然无存。

但是斯特洛夫，这个本性难移的小丑，对于美，却有着诚实，真挚的理解，就像
他灵魂的诚实，真挚一样。美对他来说，就像信徒心中的上帝，当他真看见了，
却感到害怕。
#+end_quote

斯特里克兰来到塔希提岛，便定居了下来，相对于荷兰，这才是故乡：
#+begin_quote
有些人，并未生在他们的理想之所。机缘将他们偶然抛入某种环境，他们却始终
对心中的故土满怀乡愁；这故乡在哪里，他们并不知道。在他们的出生地，他们
是异乡人，从童年时代就熟悉的林荫小巷，或者曾经玩耍过的拥挤街道，只不过
是人生旅途中的驿站。他们仿佛身处异地，举目无亲，孤身一人。也许，正是这
种陌生感，才让他们远走他乡，去寻找属于他们的永恒居所。或许，某种根深蒂
固的返祖现象，让这些游子再次回到他们的祖先在远古时代就已离开的土地。有
时候，一个人偶然来到某个地方，他会神秘地感觉，这下是他始终怀想的栖身之
所。这是他一直在寻找的家园，他会在这从未见过的场景中，在他从不认识的人
群中定居下来，就好像他生来就熟悉这一切。在这里，他终于有了着落。
#+end_quote

斯特里克兰无疑个性十足：
#+begin_quote
一个人因为看到另一种生活更有意义，只经过片刻思索就抛弃大好前程，这才需
要足够的个性。勇敢走出这一步，绝不后悔，这才真有个性。
#+end_quote

结尾，“我“想象斯特里克兰的儿子在帆船上，于太平洋中，于手风琴中，头顶蔚
蓝的天空，跳着原始而疯狂的舞蹈。

** 小人物
小人物常态：
#+begin_quote
上校茫然地望向空中，我不知道有认能像他这样，故作清白。
#+end_quote

斯特里克兰夫人被迫开了一家打印店谋生，却虚荣掩饰：
#+begin_quote
但她觉得，自己开门谋生不那么体面，所以总提醒你，她出身高贵。与人谈话，
她时不时就提她认识的一些人物，让你知道，她社会地位一点儿不低。
#+end_quote

斯特里克兰夫人是痛苦的，这痛苦不会带来“高贵”，而是仇恨：
#+begin_quote
让人行动高尚的，是自满得意；而痛苦，往往使人变得心胸狭窄，充满仇恨。
#+end_quote


** Other Interesting points

#+begin_quote
要打人，就把他伤得重一些。这样你就有时间思考，接下来怎么办。
#+end_quote


* 沉默的大多数 －－ 王小波

说明“红”话语的贫之：
#+begin_quote
用它来说话都相当困难，更不要说用它来思想了。
#+end_quote

在道德的梱绑前，先诚实的面对自己。
#+begin_quote
在这世界上的一切人之中，我最希望予提升的一个，就是我自己。这话很卑鄙，
很自私，也很诚实。
#+end_quote

聪明比道德更重要：
#+begin_quote
假设我相信上帝，并且正在为善恶不分而苦恼，我就会请求上帝让我聪明到足以
明辨是非的程度，而绝不会请他让我愚蠢到让人家给我灌输善恶标准的程度。假
若上帝要我负起灌输的任务，我就要请求他让我在此项任务和下地狱中做一选择，
并且我坚定不移的决心是：选择后者。
#+end_quote

关于聪明人和愚蠢人，以及judge：
#+begin_quote
在一切价值判断之中，最坏的一种是：想得太多，太深奥，超过了某些人的理解
程度是一种罪恶。我们在体验思想的快乐时，并没有伤害到任何人；不幸的是，
总有人觉得自己手受了伤害。诚然，这种快乐不是每一个人都能体验到的，但我
们不该对此负责任。我看不出有会么理由要取消这种快乐，除非把卑鄙的嫉妒计
算在内－－这世界上有人喜欢丰富，有人喜欢单纯；我未见过喜欢丰富的人妒恨，
伤害喜欢单纯的人，我见到的情形总是相反。
#+end_quote

花剌子模信使问题：
#+begin_quote
中亚古国花剌子模有一古怪的风俗，凡是给君王带来好消息的信使，就会得到提
升，给君王带来坏消息的人则会被送去喂老虎。
#+end_quote

* 韩寒

** 三重门

#+begin_quote
他极关爱学生，把学生当数学一样爱护，学生却把他当文学一样糟践。
#+end_quote

#+begin_quote
愚蠢和幽默往往只有语气之别。

这小镇最穷的是教育最富的是教育局。

懂事只是指一种克制，不让自己的本性露出来，本性终究是本性，过久了就会自
己露出来。

所谓看破红尘就是把原本美好的红尘看成了破烂！”
#+end_quote


** 1988:我想和这个世界谈谈
#+begin_quote
丁丁哥哥说，你懂得越多，你就越像这个世界的孤儿。

我只记得我是一个查眼保健操的时候同学们有没有闭眼的人，这就是曰复一日机
械的工作带给人们的恶果。

连电话丢了，都能一个电话就搞定了。

在这样一个世界里，你用脑子想过的事情，你总是以为你已经做过了。

他们先行，我替他们收拾着因为跑太快从口袋里跌落的扑克牌，我始终跑在他们
划破的气流里，不过我也不曾觉得风阻会减小一些，只是他们替我撞过了每一堵
我可能要撞的高墙，摔落了每一道我可能要落进的沟壑，然后告诉我，这条路没
有错，继续前行吧，但是你已经用掉了一次帮助的机会，再见了朋友。
#+end_quote
