#+TITLE: Global View

Global view is a must for pretty much everything.

When doing research, most researchers read papers by keyword
search and following citations.
1. Where you got the keyword is doubtful.
2. citations can take you anywhere, you have a feeling of getting
   deeper and wider, but the problem is you don't know exactly where
   is the end, thus get anxious about it. Such feeling will also
   prevent you from entering a new field because it reminds you the
   bad memory.
Instead, I read ALL papers, from established conferences. Of course I
cannot read them into details, because that will takes 1000 years,
that is simply not scalable in terms of lifespan. I read only
titles. The best is, I read them really fast, and categorize them. At
the end, I can confidently tell two things:
1. I'm able to identify ALL important works in a field.
2. I know the trend from old time to current, so that I can predict
   future better.
I doubt that most researchers barely read papers 5 years before they
enter the field. It is sad, if nobody is writing a summation book for
a field, I cannot image how the research would just go cycle for the
past years.

* Recognition

I'm respectfully afraid to recognition, because I know it means the
level of one's thinking. I cannot imaging how another people that have
better recognition than me would think, doesn't that sounds scary????
