#+TITLE: Global View

Global view is a must for pretty much everything.

When doing research, most researchers read papers by keyword
search and following citations.
1. Where you got the keyword is doubtful.
2. citations can take you anywhere, you have a feeling of getting
   deeper and wider, but the problem is you don't know exactly where
   is the end, thus get anxious about it. Such feeling will also
   prevent you from entering a new field because it reminds you the
   bad memory.
Instead, I read ALL papers, from established conferences. Of course I
cannot read them into details, because that will takes 1000 years,
that is simply not scalable in terms of lifespan. I read only
titles. The best is, I read them really fast, and categorize them. At
the end, I can confidently tell two things:
1. I'm able to identify ALL important works in a field.
2. I know the trend from old time to current, so that I can predict
   future better.
I doubt that most researchers barely read papers 5 years before they
enter the field. It is sad, if nobody is writing a summation book for
a field, I cannot image how the research would just go cycle for the
past years.

* Cognition bias and level

The longest distance between people is the cognition difference. 

There is a term called /Curse of Knowledge/, i.e. a cognitive bias
that occurs when the communicating individuals have different level of
background cognition.  An example given in Wikipedia is that, a
brilliant professor might no longer remember the difficulties that a
young student encounters when learning a new subject.

I'm talking about a slightly different thing. I don't care about
teaching, because I think people should teach themselves most of the
time. Thus I only care about /communication/, and specifically here
I'm talking about the cognition bias in communication.  I think
cognition is strictly leveled: the lower cognition person will never
know how a higher one think, but it is exactly the opposite the other
way around.

The smartest people are those who can understand when others explain
terribly, and can make others understand even if they have an awful
understanding ability.

The more I know, the more I know I don't know. I always think there
are people who see an entirely different world that I have no access
with my current cognition level, but I always want to talk to them and
try to improve to see that fascinating world.

