#+TITLE: Collaboration

Before you collaborate, you must be independent. I do not collaborate
with dependent people.  Those thinking they are independent are
typically not, including most professionals and professors.


# Seriously, professors are those who want to have poor students to do
# the job, and take the credits, and still want to have a sense of
# usefulness of themselves. Really, you are probably just useless, there
# is no way to make you useful.

Interestingly, those who advocate collaboration all the time are those
that *rely* on collaboration, not *mastering* it. They simply are not
professional on their area without collaboration.


Collaboration itself is not wrong, but how to collaborate, what to
collaborate on, who to collaborate with are crucial to success.

Collaboration should be free, equal. If you have to agree with another
simply because he/she is your adviser, you should get out of it.

You are not asking for respect, but do for respect in return. When you
find yourself thinking "people should respect me because ...", you are
not getting there.

* About collaborate with The Boss

I don't get along with commanders who dictate. I don't like to be
bossed around, especially if it means doing something I think
useless. So just don't try too hard to force me to do in your way.
